### ISSUE TITLE
kogito-addons-quarkus-tracing-decision - jsr310 error

### ISSUE THREAD

**Issue by doogle-oss** [apache/incubator-kie-examples#1059]
With the addon kogito-addons-quarkus-tracing-decision , we get error with org.kie.kogito.tracing.decision.QuarkusDecisionTracingCollector_VertxInvoker_onEvent...invokeBean 
Error:
Java 8 date/time type `java.time.LocalDate` not supported by default. add Module "com.fasterxml.jackson:jackon-datatype-jsr310" to enable handling (through reference chain: java.util.HashMap["Date"])

Is there any configurations for this to add the library separately. Please advise.

**Comment by radtriste** [comment]
@debu999 we have that issue https://issues.redhat.com/browse/KOGITO-6319 already. It should be fixed in 1.15 release coming in the next days

**Comment by manstis** [comment]
Hi @radtriste that PR probably does not fix the issue reported for Trusty.

I am working on a fix now.

**Comment by manstis** [comment]
See https://issues.redhat.com/browse/KOGITO-6490

**Comment by manstis** [comment]
The change has been [merged](https://github.com/kiegroup/kogito-runtimes/pull/1829) and should be in `1.16.0`

Please feel free to try with the latest `SNAPSHOT` and feedback any issues.
